<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MusicDistribution.Application\MusicDistribution.Application.csproj" />
    <ProjectReference Include="..\MusicDistribution.Domain\MusicDistribution.Domain.csproj" />
  </ItemGroup>
</Project>
