// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicDistribution.Infrastructure.Data;

#nullable disable

namespace MusicDistribution.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicDistribution.Domain.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Egypt",
                            Email = "nour.eldin@example.com",
                            Name = "Nour El Din"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Lebanon",
                            Email = "maya.hassan@example.com",
                            Name = "Maya Hassan"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Jordan",
                            Email = "omar.farouk@example.com",
                            Name = "Omar Farouk"
                        });
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.Dsp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Dsps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "YouTube"
                        });
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISRC")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ISRC")
                        .IsUnique();

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = "Arabic Pop",
                            ISRC = "EGABC2600001",
                            ReleaseDate = new DateOnly(2024, 2, 16),
                            Status = 2,
                            Title = "Cairo at Dawn"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Genre = "Indie Pop",
                            ISRC = "EGABC2600002",
                            ReleaseDate = new DateOnly(2023, 9, 8),
                            Status = 1,
                            Title = "Nile Lights"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            Genre = "Alternative",
                            ISRC = "LBDEF2600001",
                            ReleaseDate = new DateOnly(2022, 6, 3),
                            Status = 2,
                            Title = "Beirut Blue"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            Genre = "Acoustic",
                            ISRC = "LBDEF2600002",
                            ReleaseDate = new DateOnly(2024, 11, 22),
                            Status = 0,
                            Title = "Paper Moon"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 3,
                            Genre = "Electronic",
                            ISRC = "JOXYZ2600001",
                            ReleaseDate = new DateOnly(2021, 4, 14),
                            Status = 2,
                            Title = "Desert Radio"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            Genre = "R&B",
                            ISRC = "JOXYZ2600002",
                            ReleaseDate = new DateOnly(2025, 1, 10),
                            Status = 1,
                            Title = "Amman Nights"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 2,
                            Genre = "Folk",
                            ISRC = "LBDEF2600003",
                            ReleaseDate = new DateOnly(2020, 12, 1),
                            Status = 0,
                            Title = "Olive Branches"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 1,
                            Genre = "Jazz",
                            ISRC = "EGABC2600003",
                            ReleaseDate = new DateOnly(2023, 3, 27),
                            Status = 2,
                            Title = "Open Skies"
                        });
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.TrackDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DspId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DspId");

                    b.HasIndex("TrackId", "DspId")
                        .IsUnique();

                    b.ToTable("TrackDistributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DspId = 1,
                            Status = 1,
                            SubmittedAt = new DateTimeOffset(new DateTime(2024, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            DspId = 2,
                            Status = 1,
                            SubmittedAt = new DateTimeOffset(new DateTime(2024, 1, 21, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 3,
                            DspId = 3,
                            Status = 0,
                            SubmittedAt = new DateTimeOffset(new DateTime(2024, 1, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 4,
                            DspId = 1,
                            Status = 0,
                            SubmittedAt = new DateTimeOffset(new DateTime(2023, 9, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 2
                        },
                        new
                        {
                            Id = 5,
                            DspId = 2,
                            Status = 1,
                            SubmittedAt = new DateTimeOffset(new DateTime(2022, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 3
                        },
                        new
                        {
                            Id = 6,
                            DspId = 1,
                            Status = 2,
                            SubmittedAt = new DateTimeOffset(new DateTime(2024, 11, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 4
                        },
                        new
                        {
                            Id = 7,
                            DspId = 3,
                            Status = 1,
                            SubmittedAt = new DateTimeOffset(new DateTime(2021, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 5
                        },
                        new
                        {
                            Id = 8,
                            DspId = 2,
                            Status = 0,
                            SubmittedAt = new DateTimeOffset(new DateTime(2025, 1, 5, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 6
                        },
                        new
                        {
                            Id = 9,
                            DspId = 1,
                            Status = 1,
                            SubmittedAt = new DateTimeOffset(new DateTime(2023, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TrackId = 8
                        });
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.Track", b =>
                {
                    b.HasOne("MusicDistribution.Domain.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.TrackDistribution", b =>
                {
                    b.HasOne("MusicDistribution.Domain.Entities.Dsp", "Dsp")
                        .WithMany("TrackDistributions")
                        .HasForeignKey("DspId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicDistribution.Domain.Entities.Track", "Track")
                        .WithMany("TrackDistributions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dsp");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.Dsp", b =>
                {
                    b.Navigation("TrackDistributions");
                });

            modelBuilder.Entity("MusicDistribution.Domain.Entities.Track", b =>
                {
                    b.Navigation("TrackDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
